#!/usr/bin/env python3
"""
notes_projets.py — Les 24 notes annexes officielles des PROJETS DE
DÉVELOPPEMENT ET ASSIMILÉS (SYCEBNL, Partie 4, ch. 3, section 6), définies
pour le moteur de rendu générique de notes_sycebnl.py. Alimentées en
formules Excel (SUMIF sur BALANCE / BALANCE_N1) ; affectations vérifiées
contre le plan des comptes SYCEBNL. Les renvois de Notes suivent la fiche
récapitulative officielle (les renvois du bilan scanné sont incohérents,
signalés [texte officiel] dans references/partie4-ch3-...).
"""

NOTES_PROJETS = [
    {"feuille": "NOTE 1", "type": "texte",
     "titre": "INFORMATIONS OBLIGATOIRES",
     "blocs": ["A - IDENTITÉ, ORGANISATION : date de début du projet, nature "
               "du projet de développement, activité ou mission réalisée, "
               "données chiffrées (effectifs, total des ressources affectées, "
               "moyens utilisés).",
               "B - DÉCLARATION DE CONFORMITÉ AU SYSTÈME COMPTABLE DES ENTITÉS "
               "À BUT NON LUCRATIF ET FAITS MARQUANTS DE L'EXERCICE.",
               "C - RÈGLES, MÉTHODES COMPTABLES ET DÉROGATION AUX PRINCIPES "
               "COMPTABLES.",
               "D - INFORMATIONS COMPLÉMENTAIRES RELATIVES AU BILAN ET AU "
               "COMPTE D'EXPLOITATION."]},
    {"feuille": "NOTE 2", "type": "texte",
     "titre": "INFORMATIONS SPÉCIFIQUES",
     "blocs": ["A - TABLEAU EMPLOIS RESSOURCES : faits marquants.",
               "B - TABLEAU D'EXÉCUTION BUDGÉTAIRE : expliquer les écarts "
               "significatifs entre budget et réalisation.",
               "C - TABLEAU DE RÉCONCILIATION DE TRÉSORERIE : faits marquants."]},
    {"feuille": "NOTE 3A", "type": "mouvements_brut",
     "titre": "IMMOBILISATIONS BRUTES",
     "lignes": [
         ("h", "IMMOBILISATIONS INCORPORELLES"),
         ("d", "Brevets, licences, logiciels et droits similaires",
          "212,213,214", "nd"),
         ("d", "Avances et acomptes sur immobilisations incorporelles", "251", "nd"),
         ("d", "Autres immobilisations incorporelles", "218,219", "nd"),
         ("h", "IMMOBILISATIONS CORPORELLES"),
         ("d", "Terrains hors immeuble de placement", "22!2281", "nd"),
         ("d", "Terrains - immeuble de placement", "2281", "nd"),
         ("d", "Bâtiments hors immeuble de placement",
          "231,232,233,2391,2392,2393!2315,2325", "nd"),
         ("d", "Bâtiments - immeuble de placement", "2315,2325,2396", "nd"),
         ("d", "Aménagements, agencements et installations",
          "234,235,238,2394,2395,2398", "nd"),
         ("d", "Matériel, mobilier et actifs biologiques", "24!245,2495", "nd"),
         ("d", "Matériel de transport", "245,2495", "nd"),
         ("d", "Avances et acomptes sur immobilisations corporelles", "252", "nd"),
         ("h", "IMMOBILISATIONS FINANCIÈRES"),
         ("d", "Dépôts et cautionnements", "275", "nd"),
         ("d", "Autres immobilisations financières", "26,27!275", "nd"),
     ],
     "commentaires": ["Toute variation significative doit être commentée ; "
                      "joindre l'inventaire physique des immobilisations."]},
    {"feuille": "NOTE 3B", "type": "mouvements_brut",
     "titre": "BIENS PRIS EN LOCATION-ACQUISITION",
     "sous_titre": "I : crédit-bail immobilier ; M : crédit-bail mobilier ; "
                   "A : autres contrats",
     "lignes": [
         ("d", "Terrains", "2286", "nd"),
         ("d", "Bâtiments", "2316", "nd"),
         ("d", "Matériel, mobilier", "2416,2426,2446", "nd"),
         ("d", "Matériel de transport", "2456", "nd"),
     ],
     "commentaires": ["Indiquer la nature du bien, le nom du bailleur et la "
                      "durée du bail."]},
    {"feuille": "NOTE 4", "cols": "std5", "type": "table",
     "titre": "ACTIF CIRCULANT ET DETTES CIRCULANTES HAO",
     "lignes": [
         ("h", "ACTIF CIRCULANT HAO"),
         ("d", "Créances sur cessions d'immobilisations", "485", "nd"),
         ("s", "TOTAL BRUT", "brut"),
         ("d", "Dépréciations des créances HAO", "498", "nc"),
         ("s", "", "dep"),
         ("x", "TOTAL NET DE DÉPRÉCIATIONS", "={brut}-{dep}", "net"),
         ("b",),
         ("h", "DETTES CIRCULANTES HAO"),
         ("d", "Fournisseurs d'investissements", "481", "nc"),
         ("d", "Autres dettes hors activités ordinaires", "484,4998", "nc"),
         ("s", "TOTAL", "dettes"),
     ],
     "controle": ("ACTIF-D", "BA", "net"),
     "commentaires": ["Indiquer la date et la nature de l'immobilisation "
                      "achetée et/ou cédée."]},
    {"feuille": "NOTE 5", "cols": "std5", "type": "table",
     "titre": "STOCKS ET ENCOURS",
     "controle": ("ACTIF-D", "BB", "net"),
     "lignes": [
         ("d", "Biens liés à l'activité", "31", "nd"),
         ("d", "Marchandises, matières premières et fournitures liées", "32", "nd"),
         ("d", "Autres approvisionnements", "33", "nd"),
         ("d", "Dons en nature", "34", "nd"),
         ("d", "Produits finis et intermédiaires", "36", "nd"),
         ("d", "Stocks HAO", "38", "nd"),
         ("d", "Stocks en cours de route, en consignation ou en dépôt", "37", "nd"),
         ("s", "TOTAL STOCKS ET ENCOURS", "brut"),
         ("d", "Dépréciations des stocks", "39", "nc"),
         ("s", "", "dep"),
         ("x", "TOTAL NET DE DÉPRÉCIATIONS", "={brut}-{dep}", "net"),
     ]},
    {"feuille": "NOTE 6", "cols": "ech8", "type": "table",
     "titre": "CLIENTS-USAGERS ET AUTRES CRÉANCES",
     "lignes": [
         ("d", "Fournisseurs, débiteurs", "409", "nd"),
         ("d", "Clients-usagers", "41!411,419", "nd"),
         ("d", "Personnel", "42", "d"),
         ("d", "Organismes sociaux", "43", "d"),
         ("d", "État et collectivités publiques", "44", "d"),
         ("d", "Autres débiteurs divers", "47!478", "d"),
         ("s", "TOTAL BRUT", "brut"),
         ("d", "Dépréciations des créances", "490,491,492,493,494,497", "nc"),
         ("s", "", "dep"),
         ("x", "TOTAL NET DE DÉPRÉCIATIONS", "={brut}-{dep}", "net"),
     ],
     "commentaires": ["Justifier toute variation significative et les créances "
                      "anciennes."]},
    {"feuille": "NOTE 7", "cols": "std5", "type": "table",
     "titre": "DISPONIBILITÉS",
     "lignes": [
         ("d", "Chèques à encaisser", "513", "nd"),
         ("d", "Chèques à l'encaissement", "514", "nd"),
         ("d", "Cartes de crédit à encaisser", "515", "nd"),
         ("d", "Autres valeurs à encaisser", "518", "nd"),
         ("s", "TOTAL VALEURS À ENCAISSER", "vae"),
         ("d", "Banques locales", "521", "d"),
         ("d", "Banques autres États région", "522", "d"),
         ("d", "Banques, dépôt à terme et assimilés", "525", "d"),
         ("d", "Autres banques", "523,524", "d"),
         ("d", "Banques intérêts courus", "526", "nd"),
         ("d", "Banques postales", "531", "d"),
         ("d", "Autres établissements financiers", "532,533,538", "d"),
         ("d", "Établissements financiers intérêts courus", "536", "nd"),
         ("d", "Instruments de monnaie électronique", "55", "nd"),
         ("d", "Caisse", "57", "nd"),
         ("s", "TOTAL BANQUES ET CAISSES", "banques"),
         ("d", "Dépréciations", "591,592,593,595", "nc"),
         ("s", "", "dep"),
         ("x", "TOTAL NET DE DÉPRÉCIATIONS", "={vae}+{banques}-{dep}", "net"),
     ],
     "commentaires": ["Indiquer la date de rapprochement des comptes bancaires "
                      "et la date d'inventaire de la caisse."]},
    {"feuille": "NOTE 8", "cols": "std5", "type": "table",
     "titre": "ÉCARTS DE CONVERSION",
     "lignes": [
         ("d", "Écarts de conversion-actif (détailler les créances et dettes "
               "concernées)", "478", "nd"),
         ("man", "…"),
         ("d", "Écart de conversion-passif (détailler les créances et dettes "
               "concernées)", "479", "nc"),
         ("man", "…"),
     ]},
    {"feuille": "NOTE 9", "type": "bailleur",
     "titre": "FONDS DU BAILLEUR"},
    {"feuille": "NOTE 10", "cols": "subv8", "type": "table",
     "titre": "SUBVENTIONS",
     "controle": ("PASSIF", "CD", "net"),
     "lignes": [
         ("d", "État", "1411", "nc"),
         ("d", "Régions", "1412", "nc"),
         ("d", "Départements", "1413", "nc"),
         ("d", "Communes et collectivités publiques décentralisées", "1414", "nc"),
         ("d", "Entités publiques ou mixtes", "1415", "nc"),
         ("d", "Entités et organismes privés", "1416", "nc"),
         ("d", "Organismes internationaux", "1417", "nc"),
         ("d", "Autres", "1418,148", "nc"),
         ("s", "TOTAL SUBVENTIONS", "net"),
     ]},
    {"feuille": "NOTE 11", "cols": "ech8", "type": "table",
     "titre": "DETTES FINANCIÈRES ET RESSOURCES ASSIMILÉES",
     "controle": ("PASSIF", "DC", "net"),
     "lignes": [
         ("d", "Emprunts et dettes auprès des établissements de crédit", "182", "nc"),
         ("d", "Avances reçues de l'État", "183", "nc"),
         ("d", "Dépôts et cautionnements reçus", "185", "nc"),
         ("d", "Intérêts courus", "186", "nc"),
         ("d", "Autres emprunts et dettes", "181,188", "nc"),
         ("s", "TOTAL EMPRUNTS ET DETTES FINANCIÈRES", "emprunts"),
         ("d", "Crédit-bail immobilier", "1871", "nc"),
         ("d", "Crédit-bail mobilier", "1872", "nc"),
         ("d", "Location-vente", "1873", "nc"),
         ("d", "Intérêts courus (location-acquisition)", "1876", "nc"),
         ("d", "Autres dettes de location-acquisition",
          "187!1871,1872,1873,1876", "nc"),
         ("s", "TOTAL DETTES DE LOCATION-ACQUISITION", "loc"),
         ("d", "Provisions pour litiges", "191", "nc"),
         ("d", "Provisions pour pertes de change", "194", "nc"),
         ("d", "Provisions pour pensions et obligations assimilées", "196", "nc"),
         ("d", "Autres provisions pour risques et charges", "192,198", "nc"),
         ("s", "TOTAL PROVISIONS FINANCIÈRES POUR RISQUES ET CHARGES", "prov"),
         ("x", "TOTAL DETTES FINANCIÈRES ET RESSOURCES ASSIMILÉES",
          "={emprunts}+{loc}+{prov}", "net"),
     ],
     "commentaires": ["Pour chaque emprunt : date d'octroi, organisme, montant "
                      "initial, durée, garanties données."]},
    {"feuille": "NOTE 12", "cols": "ech8", "type": "table",
     "titre": "DETTES FOURNISSEURS ET ASSIMILÉES, FISCALES ET SOCIALES",
     "lignes": [
         ("d", "Fournisseurs", "40!409", "nc"),
         ("d", "Clients-usagers créditeurs", "419", "nc"),
         ("s", "DETTES FOURNISSEURS ET ASSIMILÉES", "fourn"),
         ("d", "Personnel, rémunérations dues", "422", "c"),
         ("d", "Personnel, congés à payer", "4281", "c"),
         ("d", "Charges sociales sur congés à payer", "4382", "c"),
         ("d", "Autres personnel", "421,423,424,425,427,428!4281", "c"),
         ("d", "Caisse de sécurité sociale", "431", "c"),
         ("d", "Caisse de retraite", "432", "c"),
         ("d", "Mutuelle de santé", "4331", "c"),
         ("d", "Assurance retraite", "4332", "c"),
         ("d", "Autres charges sociales et cotisations", "4333,438!4382", "c"),
         ("s", "TOTAL DETTES SOCIALES", "soc"),
         ("d", "État, autres impôts et taxes", "442,446", "c"),
         ("d", "État, TVA", "443,444,445", "c"),
         ("d", "État, impôts retenus à la source", "447", "c"),
         ("d", "Autres dettes État", "448,449", "c"),
         ("s", "TOTAL DETTES FISCALES", "fisc"),
         ("x", "TOTAL DETTES FOURNISSEURS ET ASSIMILÉES, FISCALES ET SOCIALES",
          "={fourn}+{soc}+{fisc}", "net"),
     ]},
    {"feuille": "NOTE 13", "cols": "std5", "type": "table",
     "titre": "BANQUES, CRÉDIT D'ESCOMPTE ET DE TRÉSORERIE",
     "controle": ("PASSIF", "DX", "net"),
     "lignes": [
         ("d", "Escomptes de crédits ordinaires", "565", "c"),
         ("s", "TOTAL : BANQUES, CRÉDITS D'ESCOMPTE", "esc"),
         ("d", "Banques locales", "521", "c"),
         ("d", "Banques autres États région", "522", "c"),
         ("d", "Autres banques", "523,524,525", "c"),
         ("d", "Banques, intérêts courus", "526,566", "c"),
         ("d", "Crédit de trésorerie", "561", "c"),
         ("s", "TOTAL : BANQUES, CRÉDITS DE TRÉSORERIE", "tres"),
         ("x", "TOTAL GÉNÉRAL", "={esc}+{tres}", "net"),
     ]},
    {"feuille": "NOTE 14", "cols": "std5", "type": "table",
     "titre": "REVENUS ET AUTRES PRODUITS",
     "lignes": [
         ("d", "Fonds d'administration consommés", "702", "nc"),
         ("d", "Ventes de marchandises, produits fabriqués, travaux et "
               "services", "705", "nc"),
         ("d", "Produits accessoires", "707", "nc"),
         ("d", "Production immobilisée", "72", "nc"),
         ("d", "Subventions d'exploitation", "71", "nc"),
         ("d", "Autres produits et transferts de charges d'exploitation",
          "706,708,73,75,77,78", "nc"),
         ("s", "TOTAL : REVENUS ET AUTRES PRODUITS", "net"),
     ]},
    {"feuille": "NOTE 15", "cols": "std5", "type": "table",
     "titre": "ACHATS",
     "lignes": [
         ("d", "Achats de biens et services liés à l'activité", "601", "nd"),
         ("d", "Achats de marchandises et matières premières", "602", "nd"),
         ("d", "Matières et fournitures consommables", "604", "nd"),
         ("d", "Eau, électricité, énergies et fournitures non stockées", "605", "nd"),
         ("d", "Achats autres activités", "606", "nd"),
         ("d", "Achats d'emballages", "608", "nd"),
         ("s", "TOTAL ACHATS", "net"),
     ]},
    {"feuille": "NOTE 16", "cols": "std5", "type": "table",
     "titre": "TRANSPORTS",
     "controle": ("CR", "TD", "net"),
     "lignes": [
         ("d", "Transports sur ventes", "612", "nd"),
         ("d", "Transports pour le compte de tiers", "613", "nd"),
         ("d", "Transport du personnel", "614", "nd"),
         ("d", "Transports de plis", "616", "nd"),
         ("d", "Voyages, déplacements et autres frais de transport", "618,619", "nd"),
         ("s", "TOTAL", "net"),
     ]},
    {"feuille": "NOTE 17", "cols": "std5", "type": "table",
     "titre": "SERVICES EXTÉRIEURS",
     "controle": ("CR", "TG", "net"),
     "lignes": [
         ("d", "Sous-traitance générale", "621", "nd"),
         ("d", "Locations et charges locatives", "622", "nd"),
         ("d", "Redevances de location-acquisition", "623", "nd"),
         ("d", "Entretien, réparations et maintenance", "624", "nd"),
         ("d", "Primes d'assurance", "625", "nd"),
         ("d", "Études, recherches et documentation", "626", "nd"),
         ("d", "Publicité, publications, relations publiques", "627", "nd"),
         ("d", "Frais de télécommunications", "628", "nd"),
         ("d", "Frais bancaires", "631", "nd"),
         ("d", "Rémunérations d'intermédiaires et de conseils", "632", "nd"),
         ("d", "Frais de formation du personnel", "633", "nd"),
         ("d", "Redevances pour brevets, licences, logiciels", "634", "nd"),
         ("d", "Cotisations", "635", "nd"),
         ("d", "Frais de recherche de fonds", "636", "nd"),
         ("d", "Rémunérations de personnel extérieur à l'entité", "637", "nd"),
         ("d", "Autres charges externes", "638", "nd"),
         ("s", "TOTAL", "net"),
     ]},
    {"feuille": "NOTE 18", "cols": "std5", "type": "table",
     "titre": "IMPÔTS ET TAXES",
     "controle": ("CR", "TH", "net"),
     "lignes": [
         ("d", "Impôts et taxes directs", "641", "nd"),
         ("d", "Impôts et taxes indirects", "645", "nd"),
         ("d", "Droits d'enregistrement", "646", "nd"),
         ("d", "Pénalités et amendes fiscales", "647", "nd"),
         ("d", "Autres impôts et taxes", "648", "nd"),
         ("d", "Dégrèvements et annulations des impôts et taxes (-)", "649", "nd"),
         ("s", "TOTAL", "net"),
     ]},
    {"feuille": "NOTE 19", "cols": "std5", "type": "table",
     "titre": "AUTRES CHARGES",
     "controle": ("CR", "TI", "net"),
     "lignes": [
         ("d", "Pertes sur créances", "651", "nd"),
         ("d", "Subventions accordées", "652", "nd"),
         ("d", "Dons en nature courants à distribuer", "654", "nd"),
         ("d", "Pénalités et amendes pénales", "657", "nd"),
         ("d", "Autres charges diverses", "658", "nd"),
         ("d", "Charges pour provisions pour risques à court terme "
               "d'exploitation", "659", "nd"),
         ("s", "TOTAL", "net"),
     ],
     "commentaires": ["Indiquer les organismes bénéficiaires des dons."]},
    {"feuille": "NOTE 20A", "cols": "std5", "type": "table",
     "titre": "CHARGES DE PERSONNEL",
     "controle": ("CR", "TJ", "net"),
     "lignes": [
         ("d", "Rémunérations directes versées au personnel national", "661", "nd"),
         ("d", "Rémunérations directes versées au personnel non national",
          "662", "nd"),
         ("d", "Indemnités forfaitaires versées au personnel", "663", "nd"),
         ("d", "Charges sociales", "664", "nd"),
         ("d", "Habillement et équipement du personnel", "665", "nd"),
         ("d", "Rémunération transférée de personnel extérieur", "667", "nd"),
         ("d", "Autres charges sociales", "668", "nd"),
         ("d", "Dégrèvements et annulations des charges sociales (-)", "669", "nd"),
         ("s", "TOTAL", "net"),
     ]},
    {"feuille": "NOTE 20B", "type": "effectifs",
     "titre": "EFFECTIFS, MASSE SALARIALE ET PERSONNEL EXTÉRIEUR"},
    {"feuille": "NOTE 21", "cols": "std5", "type": "table",
     "titre": "CHARGES ET REVENUS FINANCIERS",
     "controle": ("CR", "TK", "net_frais"),
     "lignes": [
         ("d", "Intérêts des emprunts", "671", "nd"),
         ("d", "Intérêts dans loyers de location-acquisition", "672", "nd"),
         ("d", "Escomptes accordés", "673", "nd"),
         ("d", "Autres intérêts", "674", "nd"),
         ("d", "Pertes de change financières", "676", "nd"),
         ("d", "Pertes sur cessions de titres de placement", "677", "nd"),
         ("d", "Charges pour provisions à court terme à caractère financier",
          "678,679", "nd"),
         ("s", "TOTAL : FRAIS FINANCIERS", "net_frais"),
         ("d", "Intérêts de prêts et créances diverses", "771", "nc"),
         ("d", "Revenus de participations et autres titres immobilisés", "772", "nc"),
         ("d", "Escomptes obtenus", "773", "nc"),
         ("d", "Revenus de placement", "774", "nc"),
         ("d", "Gains de change financiers", "776", "nc"),
         ("d", "Gains sur cessions de titres de placement", "777,778", "nc"),
         ("d", "Transferts de charges financières", "787", "nc"),
         ("d", "Reprises de charges pour provisions à court terme à caractère "
               "financier", "779", "nc"),
         ("s", "TOTAL : REVENUS FINANCIERS", "revenus"),
         ("x", "TOTAL (revenus - frais)", "={revenus}-{net_frais}", "net"),
     ]},
    {"feuille": "NOTE 22", "type": "mouvements_prov",
     "titre": "DOTATIONS ET CHARGES POUR PROVISIONS",
     "lignes": [
         ("d", "Provisions pour risques et charges", "19", "nc", "F"),
         ("d", "Dépréciations des immobilisations", "29", "nc", "E"),
         ("s", "TOTAL : DOTATIONS", None),
         ("d", "Dépréciations des stocks et en-cours", "39", "nc", "E"),
         ("d", "Dépréciations des comptes de tiers", "490,491,492,493,494,497",
          "nc", "E"),
         ("d", "Dépréciations des comptes de créances HAO", "498", "nc", "H"),
         ("d", "Dépréciations de trésorerie", "591,592,593,595", "nc", "F"),
         ("d", "Provisions pour risques à court terme", "499,599!4998", "nc", "E"),
         ("s", "TOTAL : CHARGES POUR DÉPRÉCIATIONS ET PROVISIONS", None),
     ]},
    {"feuille": "NOTE 23", "cols": "std5", "type": "table",
     "titre": "AUTRES CHARGES ET PRODUITS HAO",
     "lignes": [
         ("d", "Charges H.A.O. constatées (compte 831)", "831", "nd"),
         ("d", "Dons en nature H.A.O. (compte 832)", "832", "nd"),
         ("d", "Pertes sur créances HAO", "834", "nd"),
         ("d", "Abandons de créances consentis", "836", "nd"),
         ("d", "Charges pour provisions pour risques à court terme HAO",
          "838,839", "nd"),
         ("d", "Dotations hors activités ordinaires", "85", "nd"),
         ("d", "Valeurs comptables des cessions d'immobilisations", "81", "nd"),
         ("d", "Variations de stocks de dons en nature HAO (+/-)", "87", "nd"),
         ("s", "TOTAL : AUTRES CHARGES HAO", "charges"),
         ("d", "Produits H.A.O. constatés (compte 841)", "841", "nc"),
         ("d", "Contributions volontaires en nature (compte 842)", "842", "nc"),
         ("d", "Contributions volontaires en numéraire", "843", "nc"),
         ("d", "Abandons de créances obtenus", "846", "nc"),
         ("d", "Transferts de produits H.A.O.", "848", "nc"),
         ("d", "Reprises de charges et provisions à court terme HAO", "849", "nc"),
         ("d", "Reprises d'amortissements, provisions et dépréciations H.A.O.",
          "86", "nc"),
         ("d", "Produits des cessions d'immobilisations", "82", "nc"),
         ("d", "Subventions d'équilibre", "88", "nc"),
         ("s", "TOTAL : AUTRES PRODUITS HAO", "produits"),
         ("x", "TOTAL (produits - charges)", "={produits}-{charges}", "net"),
     ]},
    {"feuille": "NOTE 24", "type": "budget",
     "titre": "TABLEAU D'EXÉCUTION BUDGÉTAIRE"},
]
